/**
 * Loaders for the pre-computed offline datasets (generated by
 * scripts/simulate_bandits.py). Cached so multiple components share one fetch.
 */

export interface AlgoCurve {
  mean: number[];
  std: number[];
  final: number;
}

export interface RegretCurves {
  mus: number[];
  T: number;
  seeds: number;
  laiRobbinsConstant: number;
  algos: Record<string, AlgoCurve>;
}

export interface BetaTraceStep {
  t: number;
  arm: number;
  reward: number;
  samples: number[];
  alpha: number[];
  beta: number[];
}

export interface BetaSnapshots {
  mus: number[];
  seed: number;
  trace: BetaTraceStep[];
  snapshots: Record<string, BetaTraceStep>;
}

const BASE = import.meta.env.BASE_URL ?? "./";

function dataURL(name: string): string {
  return `${BASE}data/bandits/${name}`.replace(/\/\//g, "/");
}

let regretPromise: Promise<RegretCurves> | null = null;
export function loadRegretCurves(): Promise<RegretCurves> {
  if (!regretPromise) {
    regretPromise = fetch(dataURL("regret_curves_default.json")).then((r) => {
      if (!r.ok) throw new Error(`failed to load regret curves: ${r.status}`);
      return r.json() as Promise<RegretCurves>;
    });
  }
  return regretPromise;
}

let betaPromise: Promise<BetaSnapshots> | null = null;
export function loadBetaSnapshots(): Promise<BetaSnapshots> {
  if (!betaPromise) {
    betaPromise = fetch(dataURL("beta_posterior_snapshots.json")).then((r) => {
      if (!r.ok) throw new Error(`failed to load beta snapshots: ${r.status}`);
      return r.json() as Promise<BetaSnapshots>;
    });
  }
  return betaPromise;
}
